version: '3' 
services:

  spark-master:
    ##image: bde2020/spark-master:2.4.0-hadoop2.7
    image: bde2020/spark-master:3.1.1-hadoop3.2
    container_name: spark-master
    ports:
      - 8080:8080
      - 7077:7077
    environment:
      - INIT_DAEMON_STEP=setup_spark
#      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
#    env_file:
#      - ./hadoop-hive.env
    networks:
      net_pet:
        ipv4_address: 172.27.1.10
     
  spark-worker:
    image: bde2020/spark-worker:3.1.1-hadoop3.2
    container_name: spark-worker
    depends_on:
      - spark-master
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
#      - HIVE_CORE_CONF_javax_jdo_option_ConnectionURL=jdbc:postgresql://hive-metastore/metastore
    ports:
      - 8081:8081
#    env_file:
#      - ./hadoop-hive.env
    networks:
      net_pet:
        ipv4_address: 172.27.1.11

  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
      net_pet:
        ipv4_address: 172.27.1.15

  kafka:
    image: wurstmeister/kafka:2.12-2.3.0
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 172.27.1.16
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    networks:
      net_pet:
        ipv4_address: 172.27.1.16  
#
#  producer:
#    deploy:
#      replicas: 1
#    build: producer
#    container_name: producer_container
#    depends_on:
#      - kafka
#    volumes:
#      - ./datavol:/app/datavol
#    ports:
#      - "50030:50030"
#    networks:
#      net_pet:
#        ipv4_address: 172.27.1.17
#  consumer:
#    deploy:
#      replicas: 1
#    build: consumer
#    container_name: consumer_container
#    depends_on:
#      - kafka
#    volumes:
#      - ./datavol:/app/datavol
#    ports:
#      - "50031:50031"
#    networks:
#      net_pet:
#        ipv4_address: 172.27.1.18
networks:
  net_pet:
    ipam:
      driver: default
      config:
        - subnet: 172.27.0.0/16
